language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        php:
            - 7.0
            - hhvm

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v
