language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - COVERAGE=0

matrix:
    include:
        - php: 7.0
          env: COVERAGE=1

services:
  - redis-server

before_script:
  - composer install

script:
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover coverage.clover
    else
      php vendor/bin/phpunit -c phpunit.xml.dist
    fi

after_script:
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
