language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - COVERAGE=0

matrix:
    allow_failures:
        php:
            - 7.0
            - hhvm
    include:
        - php: 5.6
          env: COVERAGE=1
    exclude:
        - php: 5.6
          env: COVERAGE=0

services:
  - redis-server

before_script:
  - composer install

script:
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover coverage.clover
    else
      php vendor/bin/phpunit -c phpunit.xml.dist
    fi

after_script:
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
